### ISSUE TITLE
Navigation Bug

### ISSUE THREAD

**Issue by handlflipp** [triopsi/ice-cold#2]
While using your theme I noticed a little bug in the navigation.
In the desktop view a click on the top-level menu results in toggling the submenu to show/hide but is not redirecting to the page: 
![image](https://user-images.githubusercontent.com/72806355/116913538-e638bc00-ac49-11eb-9553-43f92213d927.png)

So when clicking on "Unternehmen" or "Leistungen" the submenu shows up or hides but is not redirecting to mydomain.tld/unternehmen or mydomain.tld/leistungen respectively.
I guess this is from the mobile version?

Thank you in advance,
Phil

**Comment by triopsi** [comment]
Thanks @handlflipp 

In fact, it's a bug. :) I just fixed it.

**Comment by handlflipp** [comment]
@triopsi thanks a lot for the quick fix ;)
